disabled_rules:
    - force_cast
    - line_length
    - vertical_whitespace
    - trailing_whitespace
        
type_body_length:
  - 600 # warning
  - 800 # error
file_length:
  warning: 500
  error: 1200